import BlurFade from "@/components/magicui/blur-fade";
import { Avatar, AvatarFallback } from "@/components/ui/avatar";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
import type { LeadershipEntry } from "@/data/resume";
import { ChevronDown } from "lucide-react";

export default function LeadershipSection({ entries }: { entries: readonly LeadershipEntry[] }) {
  if (entries.length === 0) return null;
  return <section id="leadership" className="flex w-full flex-col gap-5"><BlurFade delay={0.04}><div className="flex items-center gap-2"><span className="h-5 w-1 rounded-full bg-research" aria-hidden="true" /><h2 className="text-xl font-bold">Leadership &amp; Activities</h2></div></BlurFade><Accordion type="multiple" className="grid grid-cols-1 gap-3 md:grid-cols-2">{entries.map((entry, index) => <BlurFade key={entry.organization} delay={0.08 + index * 0.04}><AccordionItem value={entry.organization} className={`h-full rounded-xl border border-research/15 bg-card px-4 transition-colors hover:border-research/25 ${entry.secondary ? "opacity-80" : ""}`}><AccordionTrigger className="gap-3 py-4 text-left hover:no-underline"><div className="flex min-w-0 flex-1 items-start gap-3"><Avatar className="size-9 shrink-0 border border-research/20 bg-research/5"><AvatarFallback className="bg-research/5 text-[0.6rem] font-semibold text-research dark:bg-research/10" aria-hidden="true">{entry.initials}</AvatarFallback></Avatar><div className="min-w-0"><h3 className="text-base font-semibold leading-snug">{entry.organization}</h3><div className="mt-2 space-y-1">{entry.roles.map((role) => <div key={`${role.title}-${role.start}`} className="flex flex-wrap items-baseline gap-x-2 gap-y-0.5 text-sm"><span className="font-medium text-foreground">{role.title}</span><span className="text-xs text-muted-foreground">{role.start} to {role.end}</span></div>)}</div></div></div><ChevronDown className="size-4 shrink-0 transition-transform" aria-hidden="true" /></AccordionTrigger>{entry.description && <AccordionContent><p className="border-t border-research/15 pt-3 text-sm leading-relaxed text-muted-foreground">{entry.description}</p></AccordionContent>}</AccordionItem></BlurFade>)}</Accordion></section>;
}
