"use client";

import BlurFade from "@/components/magicui/blur-fade";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
import { Badge } from "@/components/ui/badge";
import type { Project, PublicationAchievement } from "@/data/resume";
import { ArrowUpRight, ChevronDown } from "lucide-react";
import Link from "next/link";
import { useId, useState } from "react";

function ResearchCard({ project }: { project: Project }) {
  const [expanded, setExpanded] = useState(false);
  const detailsId = useId();
  return <article className="h-full rounded-xl border border-research/30 bg-research/[0.025] p-4 transition-colors hover:border-research/45 dark:bg-research/[0.06]"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><Badge className="border-research/25 bg-research/10 text-research hover:bg-research/15">IEEE Research · ICAIC 2026</Badge><h3 className="mt-2 line-clamp-2 text-base font-semibold leading-snug tracking-tight">{project.title}</h3><p className="mt-1 line-clamp-2 text-sm text-muted-foreground">{project.venue}</p></div>{project.featuredMetric && <div className="shrink-0 rounded-lg border border-research/20 bg-research/[0.06] px-3 py-2 text-right"><p className="text-base font-semibold text-research">{project.featuredMetric}</p><p className="text-xs text-muted-foreground">{project.featuredMetricLabel}</p></div>}</div><p className="mt-3 line-clamp-2 text-sm leading-relaxed text-muted-foreground">{project.outcome}</p><div className="mt-3 flex flex-wrap gap-1.5">{project.approach.slice(0, 5).map((item) => <Badge key={item} variant="outline" className="min-h-6 px-2 py-0.5 text-xs">{item}</Badge>)}</div><div className="mt-3 flex flex-wrap items-center gap-2 border-t border-research/15 pt-3"><button type="button" aria-expanded={expanded} aria-controls={detailsId} onClick={() => setExpanded((value) => !value)} className="inline-flex min-h-9 items-center gap-1 rounded-md px-2 text-sm font-medium text-research transition-colors hover:bg-research/10 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring">{expanded ? "Hide" : "Details"}<ChevronDown className={`size-4 transition-transform ${expanded ? "rotate-180" : ""}`} aria-hidden="true" /></button>{project.paperUrl && <Link href={project.paperUrl} target="_blank" rel="noopener noreferrer" className="inline-flex min-h-9 items-center gap-1.5 rounded-md px-2.5 text-sm font-medium text-research transition-colors hover:bg-research/10 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring"><ArrowUpRight className="size-4" aria-hidden="true" />View Paper</Link>}</div><div id={detailsId} hidden={!expanded} className="mt-3 space-y-2 border-t border-research/15 pt-3 text-sm leading-relaxed text-muted-foreground"><p><span className="font-semibold text-foreground">Problem:</span> {project.problem}</p>{project.build && <p><span className="font-semibold text-foreground">What I built:</span> {project.build}</p>}{project.scale && <p><span className="font-semibold text-foreground">Scale:</span> {project.scale}</p>}{project.metrics && <ul className="list-disc space-y-1 pl-4">{project.metrics.map((metric) => <li key={metric}>{metric}</li>)}</ul>}</div></article>;
}

function RecognitionCard({ entry }: { entry: PublicationAchievement }) {
  const [expanded, setExpanded] = useState(false);
  const detailsId = useId();
  return <article className="rounded-xl border border-award/25 bg-award/[0.035] p-4 dark:bg-award/[0.06]"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><Badge className={entry.type === "Participation" ? "border-border bg-muted text-muted-foreground hover:bg-muted" : "border-award/25 bg-award/10 text-award hover:bg-award/15"}>{entry.badge || entry.type}</Badge><h3 className="mt-2 text-base font-semibold leading-snug">{entry.title}</h3></div>{entry.date && <span className="shrink-0 text-xs tabular-nums text-muted-foreground">{entry.date}</span>}</div><p className="mt-2 text-sm text-muted-foreground">{entry.organization}</p><div className="mt-3 flex flex-wrap items-center gap-2 border-t border-award/15 pt-3"><button type="button" aria-expanded={expanded} aria-controls={detailsId} onClick={() => setExpanded((value) => !value)} className="inline-flex min-h-8 items-center gap-1 rounded-md px-2 text-sm font-medium text-award transition-colors hover:bg-award/10 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring">{expanded ? "Hide" : "Details"}<ChevronDown className={`size-4 transition-transform ${expanded ? "rotate-180" : ""}`} aria-hidden="true" /></button>{entry.href && <Link href={entry.href} target="_blank" rel="noopener noreferrer" className="inline-flex min-h-8 items-center gap-1 font-medium text-primary hover:underline focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring">View recognition <ArrowUpRight className="size-3.5" aria-hidden="true" /></Link>}</div><div id={detailsId} hidden={!expanded} className="mt-3 space-y-2 border-t border-award/15 pt-3 text-sm leading-relaxed text-muted-foreground">{entry.project && <p className="font-medium text-foreground/80">Project: {entry.project}</p>}<p>{entry.description}</p></div></article>;
}

export default function PublicationsAchievementsSection({ entries, research }: { entries: readonly PublicationAchievement[]; research?: Project }) {
  if (entries.length === 0 && !research) return null;
  const primary = entries.find((entry) => entry.project);
  const secondary = entries.filter((entry) => entry !== primary);
  return <section id="research" className="flex flex-col gap-5"><BlurFade delay={0.04}><h2 className="text-xl font-bold tracking-tight">Research &amp; Recognition</h2></BlurFade>{(research || primary) && <div className="grid grid-cols-1 gap-4 md:grid-cols-2">{research && <BlurFade delay={0.08} className="h-full"><ResearchCard project={research} /></BlurFade>}{primary && <BlurFade delay={0.1} className="h-full"><RecognitionCard entry={primary} /></BlurFade>}</div>}{secondary.length > 0 && <Accordion type="multiple" className="flex flex-col gap-3">{secondary.map((entry, index) => <BlurFade key={`${entry.type}-${entry.title}-${entry.date || ""}`} delay={0.12 + index * 0.04}><AccordionItem value={`${entry.type}-${entry.title}`} className="rounded-xl border border-award/25 bg-award/[0.035] px-4 dark:bg-award/[0.06]"><AccordionTrigger className="gap-3 py-4 hover:no-underline [&>svg]:size-4"><div className="flex min-w-0 flex-1 flex-wrap items-center gap-x-3 gap-y-1 text-left"><Badge className="border-border bg-muted text-muted-foreground hover:bg-muted">{entry.badge || entry.type}</Badge><span className="font-semibold">{entry.title}</span>{entry.date && <span className="text-xs tabular-nums text-muted-foreground">{entry.date}</span>}</div><ChevronDown className="size-4 shrink-0 transition-transform" aria-hidden="true" /></AccordionTrigger><AccordionContent><div className="space-y-2 border-t border-award/15 pt-3 text-sm leading-relaxed text-muted-foreground"><p>{entry.organization}</p>{entry.project && <p className="font-medium text-foreground/80">Project: {entry.project}</p>}<p>{entry.description}</p></div></AccordionContent></AccordionItem></BlurFade>)}</Accordion>}</section>;
}
